# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    configs:
        my_config_1:
            toolbar: "standard"
            #uiColor: "#000000"
    toolbars:
        items:
            standard.document: [ "Source"]

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
