sonata_admin:
    templates:
        edit: edit.html.twig
    title: DSKL Administration
    title_logo: https://shadowhelix.de/images/3/38/Logo_Deutsche_Stadtkriegsliga.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
