twig:
    default_path: '%kernel.project_dir%/templates'
    auto_reload: true
when@test:
    twig:
        auto_reload: true
        strict_variables: true
when@dev:
    twig:
        auto_reload: true
