App\Entity\TeamInfo:
  properties:
    image:
      - File:
          maxSize: 4m
          mimeTypes: [image/*]
          mimeTypesMessage: Please upload a valid image
App\Entity\League:
  properties:
    activeTeams:
      - Count:
          max: 24