App\Entity\TeamInfo:
  properties:
    image:
      - File:
          maxSize: 4m
          mimeTypes: [image/*]
          mimeTypesMessage: Please upload a valid image
App\Entity\League:
  properties:
    activeTeams:
      - Count:
          min: 24
          max: 24
App\Entity\PlayDay:
  properties:
    bestPlayersOfTheDay:
      - Count:
          min: 0
          max: 13