# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'en'
    app_locales: en|de
services:

    _instanceof:
        App\Doctrine\Type\AbstractEnumTyp:
            tags: [ 'app.doctrine_enum_type' ]
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    admin.team:
        class: App\Admin\TeamAdmin
        calls:
            - [ setTemplate, [ 'show', 'TeamAdmin/show.html.twig' ] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Team, controller: ~, manager_type: orm, group: Team., label: Team }

    admin.encounter:
        class: App\Admin\EncounterAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Encounter, controller: App\Controller\EncounterAdminController, manager_type: orm, group: Season., label: Begegnungen }
    admin.relegation_encounter:
        class: App\Admin\RelegationEncounterAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\RelegationEncounter, controller: App\Controller\EncounterAdminController, manager_type: orm, group: admin., label: Relegations Begegnungen }

    admin.play_day:
        class: App\Admin\PlayDayAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\PlayDay, controller: App\Controller\PlayDayAdminController, manager_type: orm, group: Season., label: Spieltage }

    admin.team_info:
        class: App\Admin\TeamInfoAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\TeamInfo, controller: ~, manager_type: orm, group: Team., label: "Team Informationen" }

    admin.squad:
        class: App\Admin\SquadAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Squad, controller: App\Controller\SquadAdminController, manager_type: orm, group: Team., label: "Spielerschafft" }
    admin.league:
        class: App\Admin\LeagueAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\League, controller: App\Controller\LeagueAdminController, manager_type: orm, group: Season., label: "Seasons" }

    admin.team_attributes:
        class: App\Admin\TeamAttributesAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\TeamAttributes, controller: ~, manager_type: orm, group: Team., label: "Team Attribute" }

    app.menu_builder:
        class: App\Menu\Builder
        arguments: [ "@knp_menu.factory" ]

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: [ "@app.menu_builder", createMainMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
    app.team_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: [ "@app.menu_builder", createTeamMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: team } # The alias is what is used to retrieve the menu

    app.footer:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: [ "@app.menu_builder", createFooterMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: footer } # The alias is what is used to retrieve the menu

    admin.page:
        class: App\Admin\PageAdmin

        tags:
            - { name: sonata.admin, model_class: App\Entity\Page, controller: ~, manager_type: orm, group: Seiten., label: Seiten }

    admin.teaser:
        class: App\Admin\TeaserAdmin
        calls:
            - [ setTemplate, [ 'edit', 'ck_edit.html.twig' ] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\ContentElements\Teaser, controller: ~, manager_type: orm, group: Seiten., label: Teaser }

    admin.all_star:
        class: App\Admin\AllStarAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\AllStar, controller: ~, manager_type: orm, group: Season., label: "ADL Allstars" }

    admin.retrospective:
        class: App\Admin\RetrospectiveAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Retrospective, controller: ~, manager_type: orm, group: admin, label: "Saisonrückblicke" }

    admin.article:
        class: App\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Article, controller: ~, manager_type: orm, group: Seiten., label: Wipeout!-Magazin }

    admin.relegation:
        class: App\Admin\RelegationAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Relegation, controller: App\Controller\RelegationAdminController, manager_type: orm, group: Season., label: Relegation }

    admin.affiliation:
        class: App\Admin\AffiliationAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Affiliation, controller: ~, manager_type: orm, group: admin, label: "Zugehörigkeit" }
