#!/bin/bash

## #ddev-generated
## Description: Enable or disable xdebug
## Usage: c [path] [flag] [flag1] [flag2] [flag3]
## Example: "ddev sconsole"


bin/console ${1:-} ${2:-} ${3:-} ${4:-} ${5:-}
